source.. = src/main/java/,\
           src/main/resources/,\
           src/test/java/,\
           src/test/resources/
bin.includes = META-INF/,\
               .,\
               libs/,\
               libs/HdrHistogram-2.2.2.jar,\
               libs/jackson-annotations-2.17.2.jar,\
               libs/jackson-core-2.17.2.jar,\
               libs/jackson-databind-2.17.2.jar,\
               libs/jackson-datatype-jdk8-2.17.2.jar,\
               libs/jackson-datatype-jsr310-2.17.2.jar,\
               libs/jackson-module-parameter-names-2.17.2.jar,\
               libs/jakarta.annotation-api-2.1.1.jar,\
               libs/jul-to-slf4j-2.0.16.jar,\
               libs/LatencyUtils-2.0.3.jar,\
               libs/log4j-api-2.23.1.jar,\
               libs/log4j-to-slf4j-2.23.1.jar,\
               libs/logback-classic-1.5.8.jar,\
               libs/logback-core-1.5.8.jar,\
               libs/micrometer-commons-1.13.4.jar,\
               libs/micrometer-core-1.13.4.jar,\
               libs/micrometer-jakarta9-1.13.4.jar,\
               libs/micrometer-observation-1.13.4.jar,\
               libs/slf4j-api-2.0.15.jar,\
               libs/snakeyaml-2.2.jar,\
               libs/spring-aop-6.1.13.jar,\
               libs/spring-beans-6.1.13.jar,\
               libs/spring-boot-3.3.4.jar,\
               libs/spring-boot-actuator-3.3.4.jar,\
               libs/spring-boot-actuator-autoconfigure-3.3.4.jar,\
               libs/spring-boot-autoconfigure-3.3.4.jar,\
               libs/spring-boot-starter-3.3.4.jar,\
               libs/spring-boot-starter-actuator-3.3.4.jar,\
               libs/spring-boot-starter-json-3.3.4.jar,\
               libs/spring-boot-starter-logging-3.3.4.jar,\
               libs/spring-boot-starter-tomcat-3.3.4.jar,\
               libs/spring-boot-starter-web-3.3.4.jar,\
               libs/spring-context-6.1.13.jar,\
               libs/spring-core-6.1.13.jar,\
               libs/spring-expression-6.1.13.jar,\
               libs/spring-jcl-6.1.13.jar,\
               libs/spring-web-6.1.13.jar,\
               libs/spring-webmvc-6.1.13.jar,\
               libs/tomcat-embed-core-10.1.30.jar,\
               libs/tomcat-embed-el-10.1.30.jar,\
               libs/tomcat-embed-websocket-10.1.30.jar
